### PR TITLE
Add parameter/env to set custom css styles

### PR DESCRIPTION
**Pull request by hng**
This PR adds a parameter to set custom css that is used for the streamed BigBlueButton meeting.

**Example:**

To change the background color add:
`- "BBB_CUSTOM_STYLE=body {background-color: #3A92C7 !important;}"`
to the environment section of `docker-compose.yml`

_This was done as part of my work for [ColloCall](https://collocall.de) and the [Semantic Web in Libraries Conference](http://swib.org/swib21/)._

### CODE REVIEW

**Comment by mtsonline** [comment]
Hi and thanks for this one!
Did you test it with 2.3 and 2.4?
cheers

**Comment by hng** [comment]
We've tested/used it with 2.3. Tried to test it with 2.4 just now but couldn't get it to work, looks however to be a general problem with 2.4 and the live-streaming container or our server configuration. Can test again next week.

**Comment by mtsonline** [comment]
please let us know, when you had the time to test it again with 2.4. 
There was a pr to fix issues with v2.4 even before you tested - it should be compatible though.
If you still have troubles getting it to run, get back with more details so it can be solved, as most users will switch to 2.4 or already upgraded.
thanks!

**Comment by mtsonline** [comment]
@hng  had you time to test against 2.4 again? 
cheers 
Martin

**Review by mtsonline — APPROVED** [review]

**Pull request merged**
