### PR TITLE
Fix default locale setting

### LINKED ISSUE #89: Error with chat_send in stream.py
Hi, I have install BigBlueButton-liveStreaming and cannot stream with it so far :

chat_send = browser.find_elements_by_css_selector('[aria-label="Send message"]')[0]

I have copied/pasted the URL used by the 'live' user to go and join the room, and I saw that :  
Screenshot_20201120_105230

I feel like the problem comes from the modal poping up, I tried to add :
```
        print(browser.find_elements_by_css_selector('[aria-label="Play audio"]'))
        join_audio = browser.find_elements_by_css_selector('[aria-label="Play audio"]')
        if len(join_audio) > 0:
          join_audio[0].click()

```
Just to see if it would close the modal but it didn't work.

Has anyone got the same problem ?

### PR DESCRIPTION
**Pull request by thifranc**
This pull request adds a 'locale' setting for Chrome webDriver, which is 'en_US.UTF-8'.

This parameter is needed as some of the following code is relying on 'hard coded' english parameters ( ex : css selector "Send message" ).
I've also added just a lint about a variable which had a typo in it ( according to me so I may be wrong ).

This PR fixes #89 , opened by me and misunderstood at the beginning.

### CODE REVIEW

**Comment by mtsonline** [comment]
Hi, thanks for your PR. 
Would you mind to have another look at the code / source and try to remove the requirement for english?
I already removed hardcoded english strings and replaced the selenium search by other tags used in the html code of bbb. Maybe you can find tags that won't related to the language.

The problem with the english strings is, that people in the past already had removed english language completely on their bbb instances. If there is no english language available at all, setting the language to english in chrome would not help.

So your fix is great, but it would help even more if the english strings could be removed and be replaced with other tags.

cheers

**Review by sachaz — COMMENTED** [review]
Thanks helps !

**Review by sachaz — COMMENTED** [review]
Thanks helps !

**Review by sachaz — APPROVED** [review]
Thanks helps !

**Review by mtsonline — APPROVED** [review]

**Pull request merged**
